- src/main/java/org/terasology/launcher/TerasologyLauncher.java
Java is capable of using the standard system proxy set in Gnome and the Windows control panel.
See here:
http://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html
I added the necessary system property to the startup.
> Enable use of the system proxy.

- CHANGELOG.md
- README.md
- src/main/java/org/terasology/launcher/LauncherSettings.java
- src/main/java/org/terasology/launcher/game/GameDownloader.java
- src/main/java/org/terasology/launcher/game/GameJob.java
- src/main/java/org/terasology/launcher/game/GameStarter.java
- src/main/java/org/terasology/launcher/game/TerasologyGameVersion.java
- src/main/java/org/terasology/launcher/game/TerasologyGameVersionInfo.java
- src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
- src/main/java/org/terasology/launcher/util/DownloadUtils.java
~~This is a crude and incomplete first draft - NOT MERGE READY~~
But the launcher has been broken for too long and it is time to fix it (and get 2.0.0 out) even if it isn't super pretty and polished.
I'm putting this in a branch under MovingBlocks so hopefully somebody waking up any time now over in Europe can take a look and maybe tweak at it a little more (hi @skaldarnar @msteiger @Halamix2 @mkalb !) before I get back up - past 2 am here, wee.
In short two main things have been done.
* Hacky fix for detecting the engine jar correctly again. Real goofy and probably doesn't work everywhere but it lets the launcher download and launch the game again!
* Mapping has been introduced between the engine jobs and the Omega jobs in Jenkins - this works! So far as pulling back the info, it isn't …
> First pass toward launcher working with changed zip structure + Omega support

- src/main/java/org/terasology/launcher/TerasologyLauncher.java
- src/main/java/org/terasology/launcher/util/GuiUtils.java
* `GuiUtils` directory chooser is now queued on the FX thread
* the main initialization thread is again run in background
Fixes #329
(cherry picked from commit ce3fc4d)
> Make sure directory chooser dialog is run on the FX Application thread.

- src/main/java/org/terasology/launcher/TerasologyLauncher.java
- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
This is another attempt to prevent the launcher from freezing when opening links in the browser under Linux. Likely fixes #342.
> Use HostServices instead of Desktop to open files/URLs externally.

- src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
This fixes a tiny oversight made in #351 - the default log level option should be DEFAULT (no changes to engine config files) instead of DEBUG.
> Fix to provide appopriate default logging level

- src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
- src/main/java/org/terasology/launcher/settings/LauncherSettingsDecorator.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:UselessParenthesesCheck Useless parentheses around expressions should be removed to prevent any misunderstanding
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions.
Zeeshan Asghar
> Useless parentheses around expressions should be removed to prevent any misunderstanding

- src/main/resources/org/terasology/launcher/views/settings.fxml
Increased height of horizontal box in settings so that there is enough space between the Save/Cancel buttons and the border.
> Increase border height of settings box

- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
Add tooltip to the buttons. When the download button is grey, then the tooltip does not appear, but I guess that is okay.
> #324 add tooltips

- src/main/java/org/terasology/launcher/LauncherInitTask.java
- src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
- src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
- src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
- src/main/java/org/terasology/launcher/updater/SelfUpdater.java
Seems #383 did not fix all the warnings for launcher.game so I've added some more fixes. 
There seems to be a bug with slf4j and older versions of PMD which causes the GuardLogStatementJavaUtil warning to be thrown. These warnings should go away when PMD is updated (tested no warnings with PMD 5.5.1).
> Further PMD fixes

- src/main/java/org/terasology/launcher/game/GameJob.java
- src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
The job name is used as part of an url when getting the stable build, and the jenkins url does not have the underscore in it.
> remove underscore from TERASOLOGY_STABLE job name

- build.gradle
- src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
- src/test/java/org/terasology/launcher/settings/TestBaseLauncherSettings.java
- src/test/java/org/terasology/launcher/util/TestDirectoryUtils.java
- src/test/java/org/terasology/launcher/util/TestFileUtils.java
Been working on these for a while 🙂 
- TestDirectoryUtils
- TestBaseLauncherSettings
For this, I made some of the private variables in BaseLauncherSettings public as I felt it makes the test much more clearer. Do take a look and see if it's ok.
- TestFileUtils
Refer to the issue below
Run the 3 tests, they should all pass!
I did spot a issue with `FileUtils` - it calls `File.getName()` on the file in `extractZipTo()` but `getName()` has inconsistent behaviour on different platforms. When I tested it on my machine, it actually returned the full path of the `File` instead of just the name, causing the test to fail. I've commented out this last test for now. I think it might be better if we used `Files.getNameWithoutExtension()` from Guava or `FilenameUtils.getName()` from Apache, what do …
> Added tests for FileUtils, BaseLauncherSettings, DirectoryUtils

- build.gradle
- src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
- src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
- src/main/java/org/terasology/launcher/version/TerasologyLauncherVersionInfo.java
- src/test/java/org/terasology/launcher/TestingUtils.java
- src/test/java/org/terasology/launcher/game/TestGameVersions.java
- src/test/java/org/terasology/launcher/updater/TestLancherUpdater.java
This PR adds unit tests for `LauncherUpdater` and `TerasologyGameVersions`. While there is more behavior that could be tested, I wanted to limit the size of this PR - both to make it easier to review, and to get feedback on some of the change's I've needed to make.
**Added dependencies**
In order to minimize the changes needed to the codebase, I've added `Powermock` as a dependency - the only real alternative is to greatly refactor `DownloadUtils` to allow its methods to be mocked conventionally. As these changes would have no benefit other than avoiding the need for Powermock (it would require making `DownloadUtils` a singleton, or moving making its static methods instance methods of some other class), I didn't think it worthwhile.
**Changes to the codebase**
While Powermock allows the …
> Add tests for LauncherUpdater and TerasologyGameVersions

- README.md
The "gradle install" task does not seem to exist anymore. I've assumed that the proper replacement is "gradle installApp".
> Replaced gradle install with gradle installApp

- src/main/java/org/terasology/launcher/util/FileUtils.java
- src/test/java/org/terasology/launcher/util/TestFileUtils.java
This patch fixes issue #400.
It makes the `FileUtils.extractZipTo(File archive, File outputLocation)` method correctly preserve the directory structure when extracting from an archive to a directory.
The test for this method has also been rewritten to test for an archive with a folder inside it; the previous test method, in fact, was passing because it was using a zip containing only a single file, thus not revealing the problem with archives with a more complex directory structure.
I'm not sure if I should remove the dependency on Guava from the Gradle project since it's not used anywhere after removing the call to `com.google.common.io.Files.getNameWithoutExtension`, are there any plans to use it in other parts of the launcher?
> Fix zip extractor which wasn't preserving directory structure (fixes #400)

- build.gradle
Dependency was introduced in PR #395 and the only usage removed with
PR #403.
> Removes no longer needed guava dependency

- src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
- src/main/java/org/terasology/launcher/util/DirectoryUtils.java
While porting the file handling to NIO I missed two calls from `Files.list` which were not in a try-with-resources statement. This can lead to locked files or directory.
> Files.list has to be called in a try-with-resources block

- src/main/resources/org/terasology/launcher/views/application.fxml
When the Warning was added, it was created with its own HBox to correctly place it to the left.
This HBox was overlapping all social buttons, making them unreachable.
As HBox with warning button had defined prefHeight to 64 but no maxWidth, this commit sets this property, effectively preventing the overlap.
Fixes #416
1. Check out and run the launcher from latest develop branch.
1. Try to click on the social buttons - notice no animation on them is played when hovering over them and they're not clickable.
1. Checkout and run the game from this PR branch.
1. Try to click on the social buttons - notice animation being played when hovering over them and that the buttons can be clicked.
Nothing :)
> Limit size of Warning button HBox

- README.md
The project name in Dockweblate is TerasologyLauncher but in the URLs it appears as 'launcher'.
> Fixed Translation Status in README

- src/main/java/org/terasology/launcher/LauncherInitTask.java
- src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
- src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
- src/main/java/org/terasology/launcher/settings/SettingsValidationRule.java
Fixes issue #424. 
It provides a `LauncherSettingsValidator` that validates launcher settings against a set of rules before loading it from the disk and auto-corrects the settings on any violation. It also prevents the user from selecting incorrect settings from the UI.
1. First test 
- Use a 32-bit JVM to start the launcher and open settings
- Selecting max heap size greater than 1.5GB from the combo box should be impossible now
2. Second test 
- Open `TerasologyLauncherSettings.properties` before starting the game
- Set the `maxHeapSize` to `GB_2` or higher and save it
- Start the laucher from a 32-bit JVM and go to settings
- The max heap size should be back to 1.5GB in the combo box, with a warning in the log too
> Validated launcher settings for 32-bit JVM

- src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
- src/main/resources/org/terasology/launcher/views/settings.fxml
Implements the new Settings menu UI. Fixes #430 
Open the launcher and move over straight to the Settings menu. Test the UI, especially the Save and Cancel buttons. It should be able to save the configuration to `TerasologyLauncherSettings.properties`, inside the launcher's data directory.
> New Settings UI

- src/main/java/org/terasology/launcher/util/DownloadUtils.java
Catches IOException while working with HTTP connection inside `DownloadUtils::isJenkinsAvailable`. Fixes #435.
> Catches IOException in DownloadUtils::isJenkinsAvailable

- build.gradle
The final launcher distributions now bundle a given JRE. Fixes #438. 
You will need a JRE build with JavaFX in it. Download from one of the following vendors:
- [Azul Zulu](https://www.azul.com/downloads/zulu/zulufx/)
- [Bellsoft Liberica](https://bell-sw.com/pages/java-8u212/)
- [Oracle Java](https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) (_Proprietary_)
Extract the downloaded files and use `gradlew clean build -PbundleJre=/path/to/jre` to generate the ZIP packages inside `build/distributions`. Try them in any system, it'll execute the bundled JRE only.
> Bundles a JRE with the Launcher package

- src/main/java/org/terasology/launcher/game/GameStarter.java
Uses the launcher's bundled JRE to start the game. Fixes #443. 
- Start the game from the launcher
- Go to _Extras_ → _Metrics Menu_ → _System Context_
- Check the details, it should be referring to the bundled JRE
> Makes the game run using the bundled JRE

- src/test/java/org/terasology/launcher/util/TestLanguages.java
The last 13 [TerasologyLauncherPRs](http://jenkins.terasology.org/view/Launcher/job/TerasologyLauncherPRs/) builds have not been stable due to [a test failure](http://jenkins.terasology.org/view/Launcher/job/TerasologyLauncherPRs/114/testReport/), which was caused by an improper state of `Languages.java` before running the test. This PR fixes things by resetting the state of that class after running `TestLanguages.java`. It also fixes some test names in the same class.
> Fix test failure due to incorrect locale

- src/main/java/org/terasology/launcher/LauncherInitTask.java
- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
- src/main/java/org/terasology/launcher/util/GuiUtils.java
- Avoids NPEs in `GuiUtils` and `LauncherInitTaks` similarly to the work
done in #420.  
- Refactor `updateAboutTab` to use Stream API to add markdown files. The
loop over the _About_ files is refactored to use Stream API, which also
makes it easier to a void `null` values.
Both changes are based on PR #420
Closes #420 
Co-authored-by: AvaLanCS <avalancsreg@gmail.com>
> Prevent NPEs when choosing a directories and init the Launcher

- .gitattributes
Adds *.png and *.jpg entries to .gitattributes file
> Fix .gitattributes to contain binary extension rules

- src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java
- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
Both getPaneFor and getViewFor actually create a pane/view for the given URL
and don't simply get it. Therefore, renaming them.
- rename getPaneFor to createPaneFor
- rename getViewFor to createViewFor
- remove aboutViewController update from ApplicationController as it's no
longer needed there
- Start the launcher
- Check that `About` tab is still displayed correctly
> Refactor AboutViewController

- src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
- src/main/resources/org/terasology/launcher/views/settings.fxml
The settings menu offered duplicate selection boxes for the game type
and version. This was the only setting duplicated. As this might be
confusing and does not bring any value we remove it for simplicity.
Co-authored-by: jdrueckert <jd.rueckert@googlemail.com>
Start the launcher and do the following actions for different versions:
- select arbitrary combination of package type and version
- verify the following are still working (from main UI)
- download the game
- start the game
- delete the game
- verify that the settings menu looks fine (no game selection anymore).
> Remove duplicate game (type and version) selection

- config/checkstyle/suppressions.xml
- src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
- src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java
- src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
- src/main/java/org/terasology/launcher/gui/javafx/FXUtils.java
- src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
- src/main/java/org/terasology/launcher/gui/javafx/LogViewController.java
- src/main/java/org/terasology/launcher/gui/javafx/Warning.java
- src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
- src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
- src/main/java/org/terasology/launcher/util/DownloadUtils.java
- src/main/java/org/terasology/launcher/util/FileUtils.java
- src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
- src/main/java/org/terasology/launcher/util/LauncherManagedDirectory.java
- src/test/java/org/terasology/launcher/game/TestGameVersions.java
In an attempt to utilize static code analysis and code scans again I'm trying to clean up on warnings and errors reported by Checkstyle. Most of them were simple warnings (e.g., bad formatting or wrong order of modifiers). 
Others involved a bit more refactoring, like reducing the complexity in `TerasologyGameVersions`, or trying to reduce the number of arguments/parameters accepted by a method or constructor.
Nothing of this should change semantics and should be save to merge.
> Fix Checkstyle errors

- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
- src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
- src/main/java/org/terasology/launcher/packages/JenkinsHandler.java
- src/main/java/org/terasology/launcher/packages/Package.java
Uses `JenkinsHandler` to download the changelog of packages during `PackageDatabase` synchronization, and stores it in the corresponding `Package` instance. This changelog is later written to the screen using `ChangelogViewController`.
Fixes #464. 
1. Start the launcher normally
2. Select different packages from the combo-boxes
3. The corresponding changelog should be displayed immediately
> Shows changelog of selected game package

- src/main/java/org/terasology/launcher/TerasologyLauncher.java
- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
Initializes the top buttons and `ChangeListener`s for the combo boxes as soon as `application.fxml` gets loaded. This makes the UI responsive before filling it with the package details.
Fixes #473.
1. Start the launcher normally.
2. Observe the package selected by default. Do not select another!
3. If it's not installed, _Download_ button is shown and _Delete_ button is disabled. 
Otherwise, _Start_ button is shown and _Delete_ button is enabled.
4. Now install or remove the package and restart the launcher.
5. Check if the condition in step 3 is still satisfied.
For example, when _Terasology-2291_ is installed, it should look like:
And when not installed, it should look like:
> Initializes combo boxes and buttons as soon as FXML is loaded

- .gitignore
- build.gradle
- config/gradle/jre.gradle
This PR explores the usage of _tasks_ and _distributions_ (Gradle plug-in, included via the Applications plug-in) to bundle different packages per platform. 
Bundling the game via `distZip` as before should not change the output - there will be a single `TerasologyLauncher.zip` in the `build/distributions` folder **without** a bundled JRE.
```
./gradlew distZip
```
In addition, I've added a new _distribution_ called `win64` which shows how to bundle a previously downloaded JRE in a new distribution package called `TerasologyLauncher-win64.zip` (there is a task dependency which will download the JRE if it is not present).
```
./gradlew win64DistZip
```
The JRE is currently downloaded to `$projectRoot/jre/` which allows to cache it even after `gradlew clean`.
Part of #487
---
> feature(jre): Automatically bundle JRE with distributions

- src/main/java/org/terasology/launcher/config/ConfigManager.java
- src/main/java/org/terasology/launcher/config/ConfigReader.java
- src/main/java/org/terasology/launcher/config/ConfigValidator.java
- src/main/java/org/terasology/launcher/config/ConfigWriter.java
This is a follow-up to #481.
Along with some smaller follow-up changes this inverts the dependencies to break circles in the dependency graph.
Looking at the dependency graph of the `config` package I noticed a few downwards arrows. You can see them in this diagram generated by IDEA:
I'm trying to untangle them in this PR such that all arrows point upwards:
> refactor(config): Dependency Inversion on `ConfigManager` and `ConfigReader`

- src/main/java/org/terasology/launcher/TerasologyLauncher.java
- src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
- src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
- src/main/java/org/terasology/launcher/util/HostServicesWrapper.java
This introduces a wrapper around HostServices/Desktop, the `HostServicesWrapper`. This abstraction hides what technology is used to open links in the system browser.
> fix(footer): Use java.awt.Desktop as fallback for HostServices

- .github/workflows/asset-upload.yml
The GitHub Action for `4.0.0-rc.3` failed due to renamed files:
https://github.com/MovingBlocks/TerasologyLauncher/actions/runs/60387376
This fixes the asset path, and also restructures the workflow steps a bit.
_We should utilize GitHub Actions even more to ensure release assets are as expected. Don't have to uplaod them all the time, though._
> fix(action): restruce asset upload workflow and fix asset path

- buildres/linux/TerasologyLauncher.run
- TerasologyLauncher.run used hardcoded `./bin/TersologyLauncher` to start the launcher
- this fails if outside the launcher installation directory
- detecting and using the base dir with `$(dirname "$0")` fixes this
> fix(buildres): linux run script

- build.gradle
- src/main/java/org/terasology/launcher/TerasologyLauncher.java
**Problem:** Attempting to show the CrashReporter recently fails with a NPE. As a result, instead of presenting the error to the user the launcher hangs and does no longer respond, nor does it close.
**Solution:** Remove the CrashReporter for now from the launcher and exit the application directly.
> fix: Remove (failing) CrashReporter

- src/main/java/org/terasology/launcher/util/GuiUtils.java
Fixes #551. 
Though note this PR changes the method used by *all* showMessageDialog callers, not just that one about starting the game.
1. In Settings / Advanced Options, add some nonsense like `-XX:+PleaseCrash💥` to Java Arguments.
2. Run the game. (download first, if necessary.)
3. After five seconds, you should see a dialog pop up saying "Could not start the game!"
4. After dismissing that dialog the application should respond as normal. (can select menus, switch between tabs, etc.)
> fix: Don't block the application thread on message dialog

- src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
When there's a new Launcher release out, I get a Null Pointer Exception that crashes the launcher.
This fixes the immediate crash.
(Tagging #539 as related, but it needs more than just this one NPE check.)
> fix: Remove unitialized variable in LauncherUpdater

- src/main/java/org/terasology/launcher/config/ConfigValidator.java
- src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
Get rid of these parameters if present:
> fix: Remove Java 8 JVM arguments from settings

- config/gradle/jre.gradle
The culprit was that `outputs.dir unpackDir` _adds_ another output directory to some list that already exists internally. This is unnecessary and, in fact, puts a duplicate into the list of outputs (note: not a set!).
> fix: remove doubled files when bundling the JRE

- src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
- src/test/java/org/terasology/launcher/util/TestFileUtils.java
- src/test/java/org/terasology/launcher/util/TestLanguages.java
- src/test/java/org/terasology/launcher/util/TestLauncherDirectoryUtils.java
Removes no longer necessary `public` access modifiers from JUnit5 tests as it's no longer necessary to have them.
See https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods for more details.
- clone
- run `./gradlew test` - all test should still pass
I didn't touch the `TestGameRunner` tests, as it is using `Spf4jTestLogJUnitRunner` which is based on JUnit4 and there is still required to have the modifiers present. If anybody has an idea of how to approach these tests in JUnit5, I'm all ears :)
> Remove unnecessary access modifiers on JUnit5 tests

- src/main/java/org/terasology/launcher/LauncherConfiguration.java
- src/main/java/org/terasology/launcher/NullLauncherConfiguration.java
- src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
- src/main/java/org/terasology/launcher/settings/LauncherSettings.java
Follow up to #603 by reverting the deprecations we put on several classes in anticipation of the adoption of `Config`. As the supposed replacement was just removed the deprecations no longer hold.
> chore: remove deprecations on LauncherConfig and LauncherSettings

- .github/workflows/push-validation.yml
Enables [check-run-reporter](https://www.check-run-reporter.com) for this repository to get a better overview of failed tests and checkstyle reports. The plan for open source projects is without costs.
The reporting is by no means perfect, but maybe it helps in one or another situation. If anyone finds better tooling for this we can give that a try...
I've already added the `CHECK_RUN_REPORTER_TOKEN` secret in the repository settings.
This also includes a small change so that the push validation is only executed once per PR or commit to master (for PRs within the repository we run the check twice before).
> build(ci): enable check-run-reporter for push validation

- .idea/dictionaries/kevint.xml
- build.gradle
- src/test/java/org/terasology/launcher/game/TestRunGameTask.java
Fixes the flaky TestRunGameTask.testSuccessEvent test referred to in #611.
I didn't exactly get a foolproof reproduction plan, but setting my JDK to Java 15 (as is used by the push-validation workflow) and having IntelliJ IDEA run the testSuccessEvent task "until failure" would trigger it within a minute.
I wasn't as successful in triggering a race condition in testFastExit, but it does use the same technique so I applied it there as well.
Instead of using properties or events, as my comment in #611 proposed, I used [Platform.runLater](https://openjfx.io/javadoc/15/javafx.graphics/javafx/application/Platform.html#runLater(java.lang.Runnable)) to queue the handler to run on the application thread.
I did spend a few minutes looking for a way to use one of the other abstractions but it …
> fix(tests): fix flaky TestRunGameTask tests

- src/test/java/org/terasology/launcher/game/TestRunGameTask.java
@skaldarnar, I found `waitForFxEvents` in more places than I expected. Were these tests observed to fail with race conditions too, or did we get extras as a “better safe than sorry” sort of thing?
I don't expect these tests to have the same type of race condition as `testSuccessEvent` did, as they don't do the same sort of building-a-list-from-multiple-threads thing and they don't add any event handlers.
Let me know if we have build results somewhere showing that they _do_ fail; that would point us toward some other cause I overlooked.
> chore(tests): remove extraneous waitForFxEvents calls

- build.gradle
- src/main/java/org/terasology/launcher/repositories/Jenkins.java
- src/main/java/org/terasology/launcher/repositories/JenkinsClient.java
- src/main/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapter.java
- src/main/java/org/terasology/launcher/repositories/RepositoryManager.java
- src/test/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapterTest.java
<table>
<tr>
<td> <b>input</b>
<td> nothing (the adapter itself is initialized with a release specification)
<tr>
<td> <b>action</b>
<td> <s>IO and</s> processing of server resource(s) to internal data
<tr>
<td> <b>output</b>
<td> the list of available releases
</table>
- `JenkinsClient`         - for requesting build information in internal format and fetch files
- `module.*`              - the internal data model
- `repositories.Jenkins`  - typed representation of the JSON model
- fetch Jenkins build information via `JenkinsClient`
- process the content into a list of results
- for each element in the content 
- compute another URL from the element 
- ~~open another connection to that URL~~ 
- use `JenkinsClient` to fetch the content of the file
- continue processing
> fix(repositories): make JenkinsRepositoryAdapter more resilient

- src/main/java/org/terasology/launcher/model/GameRelease.java
- src/main/java/org/terasology/launcher/model/ReleaseMetadata.java
- src/main/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapter.java
- src/main/java/org/terasology/launcher/repositories/LegacyJenkinsRepositoryAdapter.java
- src/test/java/org/terasology/launcher/repositories/JenkinsPayload.java
- src/test/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapterTest.java
- src/test/java/org/terasology/launcher/repositories/LegacyJenkinsRepositoryAdapterCompatibilityTest.java
- src/test/java/org/terasology/launcher/repositories/LegacyJenkinsRepositoryAdapterTest.java
The determination whether we are starting a LWJGL v2 or v3 game in `ApplicationController` fails with a `NumberFormatException` as the version string of the game release is no longer a plain build number. Therefore, the comment in https://github.com/MovingBlocks/TerasologyLauncher/blob/master/src/main/java/org/terasology/launcher/ui/ApplicationController.java#L341-L352 became more important.
I've decided to move this flag to the `GameRelease`, and implement the determination in the repository adapters (I think this works until we have better identifiers/versions for the game packages itself). 
(_The new logic is not used yet, but only activated in #628. In hindsight, I should have done only the refactoring first, then added the determination logic plus tests, and only then switch to the …
> refactor(model): add ReleaseMetadata container

- src/test/java/org/terasology/launcher/repositories/JenkinsPayload.java
- src/test/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapterTest.java
Address the checkstyle warnings recently introduced by correctly splitting the test payload data into V1 and V2 sub-classes.
> chore: sort test payloads into V1 and V2 (addresses checkstyle warnings)

- build.gradle
Contributes to https://github.com/MovingBlocks/Terasology/issues/4582  
Fixes #635
> chore: remove jcenter dependency

- build.gradle
seems https://github.com/MovingBlocks/TerasologyLauncher/pull/636 missed an occurrence of `jcenter()`
> build: remove jcenter

- src/main/java/org/terasology/launcher/settings/LauncherSettings.java
This tended to happen if this setting was an empty string.
Make sure the launcher Settings doesn't define any extra game parameters.
Start a game and make sure there's no error or warning in the logs about `unrecognized argument ""`.
> fix(LauncherSettings): do not send a zero-length argument

- src/main/java/org/terasology/launcher/game/GameManager.java
- src/main/java/org/terasology/launcher/repositories/JenkinsClient.java
- src/main/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapter.java
- src/main/java/org/terasology/launcher/repositories/ReleaseRepository.java
- src/main/java/org/terasology/launcher/tasks/DownloadTask.java
- src/main/java/org/terasology/launcher/util/DownloadException.java
- src/main/java/org/terasology/launcher/util/DownloadUtils.java
- src/test/java/org/terasology/launcher/repositories/JenkinsClientTest.java
I was trying to review another PR and I noticed none of the preview releases were showing up. One of our Jenkins-as-repository / HTTPS / redirect sorts of issues. So I tried swapping out the JenkinsClient#openStream implementation for one that used the newer HttpClient from Java 11.
We do get more control of how redirects are handled and more visibility in to the HTTP response if needed for troubleshooting.
Looks to be successfully following the redirects too.
It is also awfully verbose for this simple use case.
then I spent like two hours going through mailing list archives looking for the part where someone explained why HttpRequest takes a `URI`, not a `URL`. Surely that must have been a FAQ while it was going through its development and incubator phase, right? But I haven't found an …
> chore(JenkinsClient): use new HTTP client with better diagnostics

- src/main/java/org/terasology/launcher/game/GameService.java
Due to the two arguments being flipped selecting reasonable values (max memory >= min/initial memory) in the settings UI would lead to the game not starting properly with the following error message:
```
11:28:57.001 [GameService-0] INFO  o.t.launcher.game.RunGameTask - Game output: Error occurred during initialization of VM
11:28:57.001 [GameService-0] INFO  o.t.launcher.game.RunGameTask - Game output: Initial heap size set to a larger value than the maximum heap size
11:28:57.004 [GameService-0] DEBUG o.t.launcher.game.RunGameTask - Game closed with the exit value '1'.
```
Passing in the values in the right order fixes this.
> fix: pass JVM heap settings in correct order to GameStarter

- src/main/java/org/terasology/launcher/TerasologyLauncher.java
- src/main/java/org/terasology/launcher/ui/ApplicationController.java
**This PR contains no semantic or functional changes.**
We're unpacking all members from the LauncherConfiguration to pass separately to the ApplicationController when showing the main stage.
Instead, pass the configuration object as is, and take the respective information out as needed in ApplicationController#update itself.
> chore: pass LauncherConfiguration to ApplicationController#update

- build.gradle
- src/main/java/org/terasology/launcher/LauncherInitTask.java
- src/main/java/org/terasology/launcher/settings/Settings.java
- src/main/java/org/terasology/launcher/ui/ApplicationController.java
- src/main/java/org/terasology/launcher/ui/SettingsController.java
This prepares `Settings` to take over the role of `LauncherSettings` as source of truth for the launcher settings.
The information is stored in JavaFX properties wrapping the actual value. The use of properties allows for reactive bindings to simplify automatic updates of the UI.
When storig a (legacy) `LauncherSettings` object we also deserialize an equivalent `Settings` object to JSON. Vice versa, we can also read `Settings` from a JSON file.
The new `Settings` object is not yet used.
- feat: evolve `Settings` to an FX property-based settings object
- feat: use fx-json to automate de-/encoding of JavaFX properties
**This PR has no semantic or funcational changes.**
However, you can test that the `Settings` object is properly serialized alongside the `.properties' file. The content …
> feat: prepare for JavaFX-property-based launcher settings

- build.gradle
- src/main/java/org/terasology/launcher/LauncherInitTask.java
- src/main/java/org/terasology/launcher/settings/Settings.java
- src/main/java/org/terasology/launcher/ui/ApplicationController.java
- src/main/java/org/terasology/launcher/ui/SettingsController.java
- src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
Since it is the decision of `Settings` what file types to write, the file path should not be passed in from the outside. Instead, just the folder path can be controlled.
As a consequence, the exact file name(s) are an implementation detail and no longer need to be exposed by `Settings`.
Ensure `gradlew test` is still passing. 
When starting the launcher and changing settings, they should be properly picked up after a re-start.
---
Contributes to #522
Based on #665
> refactor: change API of Settings#load/store to use folder path

- .github/workflows/push-validation.yml
Update the Github actions in `push-validation`.
- `actions/setup-java` now has built-in support for Gradle caching, no need to configure `actions/cache` manually
- upgrade `actions/...` to latest versions
- upgrade `check-run-reporter` from 2.0.0 to 2.11.1
> build(github): update actions

- docs/Create-a-Release.md
This PR adds a new guide to `docs/` explaining the necessary steps to create a launcher release.
Contributes to #675.
> doc: add release guide

- src/main/java/org/terasology/launcher/util/I18N.java
Build up an index at runtime to remember which translations are missing and only log them once.
Go to the launcher settings and change the language.
Select a langauge with missing translations (German, French, and Italian definitely have missing translations for some labels).
The launcher log should print WARN logs about the missing translations only once.
Switching back and forth between those locales should not yield further log output.
Based on  #679.
> i18n: reduce log spam for missing labels

- src/main/java/org/terasology/launcher/LauncherInitTask.java
- src/main/java/org/terasology/launcher/game/GameManager.java
- src/main/java/org/terasology/launcher/repositories/RepositoryManager.java
- src/main/java/org/terasology/launcher/ui/ApplicationController.java
- src/main/java/org/terasology/launcher/ui/FooterController.java
- src/main/java/org/terasology/launcher/util/I18N.java
- src/main/resources/org/terasology/launcher/views/application.fxml
- chore: remove unused code; add doc comments
- feat: disable game profile selection (fixed on OMEGA)
- feat: remove profile box from both FXML and `ApplicationController`
- fix: check for remaining disk space each time the installed games change
- chore: move more initialization code from `ApplicationController#update` to `ApplicationController#initialize`
- feat: use more bindings in `FooterController`
Contributes to #677.
Start the launcher.
The game profile selection box ("Terasology" vs "Terasology Lite") should no longer be visible.
The game release selection box should contain the releases (and pre-releases, if enabled in the settings) of Omega builds.
Downloading and starting Omega releases should still work as before.
> **Note:** Previously installed engine-only releases will no …
> feat: remove game profile selection (fixed on OMEGA)

- src/test/java/org/terasology/launcher/util/ResourceTests.java
A simple (JavaFX) unit test to ensure that the flag icons for the supported locales can be loaded.
Run the new test to check that it succeeds.
```
gradlew test
```
I checked the negative case locally by adding a new locale (`new Locale("nl")`)  to the list of supported locales in `I18N.java` and observed test failure for that locale, as would be expected.
Nothing.
> test: add test to ensure that all supported languages have language flag icons

- src/main/java/org/terasology/launcher/LauncherInitTask.java
-Updated the download URL from https://terasology.org/download to https://terasology.org/downloads/
Fixes #690
> fix: updated the download URL

- src/main/java/org/terasology/launcher/repositories/GithubRepositoryAdapter.java
Instead of blindly logging the stacktrace of exceptions the launcher now checks for an `HTTPException` and whether the status code is -1, indiciating a network issue, for instance, when running offline.
Thus, we should only log in exceptional cases.
This does not affect any functionality of the launcher when run offline, though.
Start the launcher when offline and observe the logs. There should be less stacktraces printed from the GitHub repository adapter.
Nothing.
> chore: handle offline mode more graceful

- src/main/java/org/terasology/launcher/settings/LauncherSettings.java
- src/main/java/org/terasology/launcher/settings/Settings.java
- src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
Removes code that wrote to a legacy TerasologyLauncherSettings.properties
Still reads from the legacy file if it cannot find the new JSON config
Deletes some code that was marked for deletion via code comments
1. Build the launcher with the changes in this PR
2. Find the directory where the launcher stores its configuration files. On Windows, it's under <user>/AppData/Roaming/TerasologyLauncher by default
3. However you prefer, create or modify your own TerasologyLauncherSettings.properties to include these modified field values: 
```
maxHeapSize=MB_512
initialHeapSize=MB_512
```
4. If settings.json exists, delete it.
5. Run the development build of the launcher.
6. It will prompt you to select a game data folder (this is the current behavior of the release version of the launcher). Go …
> fix(settings): stop writing legacy configuration file

- src/main/java/org/terasology/launcher/ui/SettingsController.java
Fixes https://github.com/MovingBlocks/TerasologyLauncher/issues/686.
Looks like there's only really one file where the old `LauncherSettings` are still used incorrectly (that's `SettingsController`), and it's just to get a bunch of default values. So we retrieve these from the new class instead!
Affects `userGameSettings` and `userJavaSettings` (under "advanced options") so play around with these. I even added a couple of extra logging options just to be sure!
None!
> Remove use of old Launcher Settings

- src/main/java/org/terasology/launcher/repositories/JenkinsClient.java
A small change to handle unsuccessful requests via the `JenkinsClient` more gracefully.
Currently, a request failing with 4xx or 5xx will print a WARN log message and the whole stacktrace.
```
17:56:01.186 [ForkJoinPool.commonPool-worker-19] WARN  o.t.l.repositories.JenkinsClient - Failed to read JSON from 'http://jenkins.terasology.io/teraorg/job/Terasology/job/Omega/job/develop/api/json?tree=builds[number,timestamp,result,artifacts[fileName,relativePath],url]'
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
at com.google.gson.Gson.fromJson(Gson.java:932)
at …
```
> fix: handle unsuccessful requests in JenkinsClient better

- src/main/java/org/terasology/launcher/game/GameService.java
- src/main/java/org/terasology/launcher/game/GameStarter.java
- src/main/java/org/terasology/launcher/game/GameVersionNotSupportedException.java
- src/main/java/org/terasology/launcher/game/VersionHistory.java
- src/main/java/org/terasology/launcher/ui/ApplicationController.java
- src/test/java/org/terasology/launcher/game/TestGameStarter.java
To prepare for Java runtime management in the launcher  this PR introduces 
- an entry to `VersionHistory` to denote the first (upcoming) game release to require Java 17
- add a new checked exception to bail out in case the launcher tries to start an unsupported version
In this state, the user experience is not great, but at least the launcher is not crashing an the error message shows a somewhat useful message.
This could be released as a minor or patch release to harden the launcher against new releases and release candidates requiring that no longe work with the Java 11 shipped with the launcher.
Start the launcher and check that everything is working as expected.
To see the error message you can change the version in `VersionHistory.JAVA17` to something lower like `4.0.0` and try to …
> feat: prepare runtime management

- build.gradle
- buildSrc/build.gradle
- config/gradle/jre.gradle
- settings.gradle
prepare convert to kotlin by adopting syntax. fix one bug which prevents re-run build on linux, as default permission on extract zip file is read only and 2nd run fails with permission denied.
> build(gradle): prepare gradle convert to kotlin, permit rerun build locally
