build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/org/terasology/launcher/LauncherInitTask.java
src/main/java/org/terasology/launcher/TerasologyLauncher.java

Init thread fix

---

src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java

* disable animations on collapse/expand actions
* expand first pane by default (if present)
Fixes #318

Disable animations of accordion panes.

---

build.gradle
src/main/java/org/terasology/launcher/LauncherInitTask.java
src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
src/main/java/org/terasology/launcher/util/BundleUtils.java
src/main/java/org/terasology/launcher/util/DirectoryUtils.java
src/main/java/org/terasology/launcher/util/GuiUtils.java
src/main/resources/org/terasology/launcher/bundle/FXMLBundle.properties
src/main/resources/org/terasology/launcher/views/update_dialog.fxml

Major cleanup of old swing dependencies.

FX Cleanup

---

src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java

Fixes #336 
@Cervator - can you please test (it works on Linux, cannot test on Windows atm)

Added a padding to webviews.

---

src/main/java/org/terasology/launcher/game/TerasologyGameVersionInfo.java
src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
src/main/java/org/terasology/launcher/updater/LauncherUpdater.java

This pull request is focused on resolving occurrences of Sonar rule 
pmd:ConsecutiveAppendsShouldReuse Consecutive Appends Should Reuse
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/pmd:ConsecutiveAppendsShouldReuse
Please let me know if you have any questions.
Zeeshan Asghar

Consecutive Appends Should Reuse

---

src/main/java/org/terasology/launcher/game/GameRunner.java
src/main/java/org/terasology/launcher/game/GameStarter.java
src/main/java/org/terasology/launcher/game/TerasologyGameVersion.java
src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
src/main/java/org/terasology/launcher/game/VersionItem.java

Had some free time 🙂
All 51 warnings for launcher.game should be fixed

Fixed all PMD warnings for org.terasology.launcher.game

---

src/test/java/org/terasology/launcher/game/TestGameRunner.java

Tests all of the logging conditions GameRunner should meet.

GameRunner test (GCI)

---

src/main/java/org/terasology/launcher/LauncherConfiguration.java
src/main/java/org/terasology/launcher/LauncherInitTask.java
src/main/java/org/terasology/launcher/game/GameDownloader.java
src/main/java/org/terasology/launcher/game/GameStarter.java
src/main/java/org/terasology/launcher/game/TerasologyGameVersion.java
src/main/java/org/terasology/launcher/game/TerasologyGameVersionInfo.java
src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
src/main/java/org/terasology/launcher/settings/AbstractLauncherSettings.java
src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
src/main/java/org/terasology/launcher/settings/LauncherSettingsDecorator.java
src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
src/main/java/org/terasology/launcher/updater/SelfUpdater.java
src/main/java/org/terasology/launcher/util/DirectoryUtils.java
src/main/java/org/terasology/launcher/util/DownloadUtils.java
src/main/java/org/terasology/launcher/util/FileUtils.java
src/main/java/org/terasology/launcher/util/GameDataDirectoryNames.java
src/main/java/org/terasology/launcher/util/GuiUtils.java
src/main/java/org/terasology/launcher/util/visitor/ArchiveCopyVisitor.java
src/main/java/org/terasology/launcher/util/visitor/DeleteFileVisitor.java
src/main/java/org/terasology/launcher/util/visitor/LocalCopyVisitor.java
src/test/java/org/terasology/launcher/TestingUtils.java
src/test/java/org/terasology/launcher/game/TestGameRunner.java
src/test/java/org/terasology/launcher/game/TestGameVersions.java
src/test/java/org/terasology/launcher/settings/TestBaseLauncherSettings.java
src/test/java/org/terasology/launcher/updater/TestLancherUpdater.java
src/test/java/org/terasology/launcher/util/TestDirectoryUtils.java
src/test/java/org/terasology/launcher/util/TestFileUtils.java

Implements #406 
**Done**
**Todo**
**KNOWN bugs**
- ~~AccessDeniedException when downloading the zip, deleting and downloading again~~

Switch file handling to Java NIO

---

CHANGELOG.md
src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
src/main/resources/org/terasology/launcher/views/application.fxml

I have merged the Download & Play buttons to be a single button. Depending on the state of the selected build, it will either set the graphic of the button to be the "play" image or the "download" image. The functionality of the button will also change depending on the state of the selected build. This PR should close issue #397 
I am quite new to JavaFX so any feedback would be greatly appreciated!

Merged Download & Play Buttons

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/maven-settings.xml
.gitignore

- adds devcontainer for Visual Studio Code
- a devcontainer is a Docker container as a full-featured development environment
- the devcontainer.json file configures devcontainer access or creation by vscode
- more info at https://code.visualstudio.com/docs/remote/containers

Add devcontainer for vscode

---

src/main/java/org/terasology/launcher/TerasologyLauncher.java
src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
src/main/java/org/terasology/launcher/gui/javafx/FXUtils.java
src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
src/main/java/org/terasology/launcher/gui/javafx/Warning.java
src/main/resources/org/terasology/launcher/views/application.fxml
src/main/resources/org/terasology/launcher/views/footer.fxml

- add `footer.fxml`
- add `FooterController` and move code related to the footer area with
social media buttons
- share UI code via `FXUtils`
Part of #462
Co-authored-by: jdrueckert <jd.rueckert@googlemail.com>

Extract Footer from main application controller

---

src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
src/main/resources/org/terasology/launcher/views/application.fxml
src/main/resources/org/terasology/launcher/views/changelog-view.fxml

- add `changelog-view.fxml`
- add `ChangelogViewController` and move (old) code related to compute
and display the changelog
- introduce a property with binding to hook up the changelog update
Contributes to #464.
Part of #462
Co-authored-by: jdrueckert <jd.rueckert@googlemail.com>
This won't make the changelog work again yet, needs more work from you, @praj-foss  😉

Extract ChangelogView from main application controller

---

.github/workflows/gradle.yml

- run `.gradlew test` instead of `./gradlew build` to avoid dist tasks

fix: github action on push

---

src/main/java/org/terasology/launcher/util/FileUtils.java
src/main/java/org/terasology/launcher/util/OperatingSystem.java

chore: simplify FileUtils and fix "Unknown Windows"

---

.github/workflows/push-validation.yml

This will also build PRs that come from forks, as opposed to `push` events which only trigger on this very repository.

fix(action): Trigger push-validation for PRs

---

build.gradle
src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java

chore: Use new parser for markdown rendering

---

build.gradle
src/main/java/module-info.java

Fixes for tests and running in modularity world
* ./gradlew run -- launcher started
* ./gradlew test -- tests passed

Fixes to modularity. Running and testing now

---

.github/workflows/push-validation.yml
build.gradle
src/main/java/org/terasology/launcher/gui/javafx/Effects.java

Various small adjustments and improvements to the code base and mostly the CI pipeline. 
- update from JDK 14 >>> JDK 15
- cache Gradle packages between workflow runs
- separate build, test, and analysis stages for better error messages
- fix a checkstyle error by adding a license header

ci: improve workflow

---

src/main/java/org/terasology/launcher/game/GameService.java
src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
src/main/java/org/terasology/launcher/settings/LauncherSettings.java
src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java

Base parameter for running game and lwgjl3-macos parameter within.
parameters : 
* Platforms ($platform):
* Macos
* Windows(or linux)
* Game versions($version):
* latest with lwjgl3
* stable
Test case:
1. run launcher on $platform
2. run game with version $version
3. should run success.

feature(lwjgl3): Add BaseJavaParameters for game, implement macos-specific lwgl3-related params.

---

src/main/java/org/terasology/launcher/game/GameService.java
src/main/java/org/terasology/launcher/game/GameStarter.java
src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
src/main/java/org/terasology/launcher/settings/LauncherSettings.java

fix: various issues

---

src/main/java/org/terasology/launcher/repositories/LegacyJenkinsRepositoryAdapter.java
src/main/java/org/terasology/launcher/repositories/RepositoryManager.java
src/test/java/org/terasology/launcher/repositories/JenkinsPayload.java
src/test/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapterTest.java
src/test/java/org/terasology/launcher/repositories/StubJenkinsClient.java

- test: move JenkinsPayload string to own class
- refactor(repositories): Inject JenkinsClient to LegacyJenkinsRepositoryAdapter
- test(repositories): Extract StubJenkinsClient from test class

test(repositories): prepare legacy adapter for testing

---

.idea/checkstyle-idea.xml
build.gradle
config/gradle/jre.gradle

Minor upgrades to the bundled Java as well as Launcher's library dependencies.
Seems _mostly_ okay here, but there are some faults in the rendering of the Changelog and documents in the About section. Should check if those are regressions or existing behavior.

build: runtime upgrade to Java 11.0.16.1 (from 11.0.7)

---

src/main/java/org/terasology/launcher/LauncherInitTask.java

- chore: remove unused function 'confirmSourcesOverwrite'
- chore: remove unused imports
The code was unused, so I hope no test needed. 
Nothing.

chore: Remove unused code
